---
- name: Create Organization
  hosts: satellite
  gather_facts: false
  vars_files: satellite_connection_credentials.yml
  tasks:
    - name: "Create CI Organization"
      redhat.satellite.organization:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        name: "{{ satellite_new_organization }}"
        state: present
